# Generated by Django 4.1.4 on 2022-12-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toppings', to='menu_app.food'),
        ),
    ]
